export const COUNTER_CHANGE = 'COUNTER_CHANGE'
export const FETCH_ALL_PARKINGS_SUCCESS = "FETCH_ALL_PARKINGS_SUCCESS"
export const FETCH_ALL_PARKINGS_FAIL = "FETCH_ALL_PARKINGS_FAIL"
export const FETCH_ONE_PARKING = "FETCH_ONE_PARKING"
export const FETCH_ONE_PARKING_FAIL = "FETCH_ONE_PARKING_FAIL"
export const FETCH_ONE_PARKING_SLOTS = "FETCH_ONE_PARKING_SLOTS"
export const FETCH_ONE_PARKING_SLOTS_FAIL = "FETCH_ONE_PARKING_SLOTS_FAIL"